fix it

diff --git a/gcc-4.8-non-fatal-compare-failure.patch b/gcc-4.8-non-fatal-compare-failure.patch
--- a/gcc-4.8-non-fatal-compare-failure.patch
+++ b/gcc-4.8-non-fatal-compare-failure.patch
@@ -1,22 +1,31 @@
---- gcc-linaro-4.8-2013.12/Makefile.in.omv~	2013-12-30 23:51:00.695409504 +0100
-+++ gcc-linaro-4.8-2013.12/Makefile.in	2013-12-30 23:51:54.912076882 +0100
-@@ -44294,7 +44294,7 @@ compare:
+--- gcc-linaro-snapshot-6.3-2017.06/Makefile.in.compare~	2017-07-07 20:39:30.682990437 +0200
++++ gcc-linaro-snapshot-6.3-2017.06/Makefile.in	2017-07-07 20:40:47.399216464 +0200
+@@ -48801,7 +48801,7 @@ compare:
  	if [ -f .bad_compare ]; then \
  	  echo "Bootstrap comparison failure!"; \
  	  cat .bad_compare; \
 -	  exit 1; \
-+	  echo "You'll want to run extra checks."; \
++	  echo Please make sure everything works.; \
  	else \
  	  echo Comparison successful.; \
- 	fi ; \
---- gcc-linaro-4.8-2013.12/Makefile.tpl.omv~	2013-12-30 23:50:07.868742144 +0100
-+++ gcc-linaro-4.8-2013.12/Makefile.tpl	2013-12-30 23:50:58.392076140 +0100
-@@ -1606,7 +1606,7 @@ do-clean: clean-stage[+id+]
+ 	fi; \
+@@ -49199,7 +49199,7 @@ compare3:
  	if [ -f .bad_compare ]; then \
  	  echo "Bootstrap comparison failure!"; \
  	  cat .bad_compare; \
 -	  exit 1; \
-+	  echo "You'll want to run extra checks."; \
++	  echo Please make sure everything works.; \
  	else \
  	  echo Comparison successful.; \
- 	fi ; \
+ 	fi; \
+--- gcc-linaro-snapshot-6.3-2017.06/Makefile.tpl.compare~	2017-07-07 20:39:30.684990391 +0200
++++ gcc-linaro-snapshot-6.3-2017.06/Makefile.tpl	2017-07-07 20:41:03.697839577 +0200
+@@ -1646,7 +1646,7 @@ do-clean: clean-stage[+id+]
+ 	if [ -f .bad_compare ]; then \
+ 	  echo "Bootstrap comparison failure!"; \
+ 	  cat .bad_compare; \
+-	  exit 1; \
++	  echo Please make sure everything works.; \
+ 	else \
+ 	  echo Comparison successful.; \
+ 	fi; \
